{
  "formatVersion": "1.1",
  "component": {
    "group": "io.github.koalaplot",
    "module": "koalaplot-core",
    "version": "0.12.1-animation-fix",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.4.1"
    }
  },
  "variants": [
    {
      "name": "metadataApiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.compose.ui",
          "module": "ui",
          "version": {
            "requires": "1.11.1"
          }
        },
        {
          "group": "org.jetbrains.compose.animation",
          "module": "animation",
          "version": {
            "requires": "1.11.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.4.10"
          }
        },
        {
          "group": "org.jetbrains.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.11.1"
          }
        },
        {
          "group": "org.jetbrains.compose.foundation",
          "module": "foundation",
          "version": {
            "requires": "1.11.1"
          }
        },
        {
          "group": "org.jetbrains.compose.material3",
          "module": "material3",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.11.0"
          }
        }
      ],
      "files": [
        {
          "name": "koalaplot-core-metadata-0.12.1-animation-fix.jar",
          "url": "koalaplot-core-0.12.1-animation-fix.jar",
          "size": 87087,
          "sha512": "f65664ae030d5e3ae67def45beaf3cb1ff3f97cb10cf01271f9dc7e8ccb4c4fc61a12679125179d857681b562a13668002c069263d6d28a2477d7d37785b290e",
          "sha256": "36e1bae41dc34728adbd0e4a46fa16f1afbe1b1f1e6f75ea3f54daca0acea018",
          "sha1": "0f238a47fb1a5262ef0b8d40d05d4d7b48acb1fc",
          "md5": "b679bd3bdc988ec57f1630af4ddf2a96"
        }
      ]
    },
    {
      "name": "metadataSourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "files": [
        {
          "name": "koalaplot-core-kotlin-0.12.1-animation-fix-sources.jar",
          "url": "koalaplot-core-0.12.1-animation-fix-sources.jar",
          "size": 146883,
          "sha512": "1e54d78b1abc265aec05ea4b94e24bafff4e9cdb9be5d6b39d4d851360418dfb82a958fc4d69cd4c036a877ed9f1a558f156fb0e3652b7a2429fd5124b8e844d",
          "sha256": "758475f62c47a6230271a8dd0d4233ef5a9f96d2ee8880afea61006bf4dfc896",
          "sha1": "64ed248007beb2dabe3574f17305b127d72093a2",
          "md5": "5dfb1cb02a3f62d78a1a969faecf3c9b"
        }
      ]
    },
    {
      "name": "androidApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "available-at": {
        "url": "../../koalaplot-core-android/0.12.1-animation-fix/koalaplot-core-android-0.12.1-animation-fix.module",
        "group": "io.github.koalaplot",
        "module": "koalaplot-core-android",
        "version": "0.12.1-animation-fix"
      }
    },
    {
      "name": "androidRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "available-at": {
        "url": "../../koalaplot-core-android/0.12.1-animation-fix/koalaplot-core-android-0.12.1-animation-fix.module",
        "group": "io.github.koalaplot",
        "module": "koalaplot-core-android",
        "version": "0.12.1-animation-fix"
      }
    },
    {
      "name": "androidSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "android",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "available-at": {
        "url": "../../koalaplot-core-android/0.12.1-animation-fix/koalaplot-core-android-0.12.1-animation-fix.module",
        "group": "io.github.koalaplot",
        "module": "koalaplot-core-android",
        "version": "0.12.1-animation-fix"
      }
    },
    {
      "name": "desktopApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../koalaplot-core-desktop/0.12.1-animation-fix/koalaplot-core-desktop-0.12.1-animation-fix.module",
        "group": "io.github.koalaplot",
        "module": "koalaplot-core-desktop",
        "version": "0.12.1-animation-fix"
      }
    },
    {
      "name": "desktopRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../koalaplot-core-desktop/0.12.1-animation-fix/koalaplot-core-desktop-0.12.1-animation-fix.module",
        "group": "io.github.koalaplot",
        "module": "koalaplot-core-desktop",
        "version": "0.12.1-animation-fix"
      }
    },
    {
      "name": "desktopSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../koalaplot-core-desktop/0.12.1-animation-fix/koalaplot-core-desktop-0.12.1-animation-fix.module",
        "group": "io.github.koalaplot",
        "module": "koalaplot-core-desktop",
        "version": "0.12.1-animation-fix"
      }
    },
    {
      "name": "iosArm64ApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../koalaplot-core-iosarm64/0.12.1-animation-fix/koalaplot-core-iosarm64-0.12.1-animation-fix.module",
        "group": "io.github.koalaplot",
        "module": "koalaplot-core-iosarm64",
        "version": "0.12.1-animation-fix"
      }
    },
    {
      "name": "iosArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../koalaplot-core-iosarm64/0.12.1-animation-fix/koalaplot-core-iosarm64-0.12.1-animation-fix.module",
        "group": "io.github.koalaplot",
        "module": "koalaplot-core-iosarm64",
        "version": "0.12.1-animation-fix"
      }
    },
    {
      "name": "iosArm64ResourcesElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.libraryelements": "kotlin-multiplatformresources",
        "org.gradle.usage": "kotlin-multiplatformresources",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../koalaplot-core-iosarm64/0.12.1-animation-fix/koalaplot-core-iosarm64-0.12.1-animation-fix.module",
        "group": "io.github.koalaplot",
        "module": "koalaplot-core-iosarm64",
        "version": "0.12.1-animation-fix"
      }
    },
    {
      "name": "iosArm64MetadataElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../koalaplot-core-iosarm64/0.12.1-animation-fix/koalaplot-core-iosarm64-0.12.1-animation-fix.module",
        "group": "io.github.koalaplot",
        "module": "koalaplot-core-iosarm64",
        "version": "0.12.1-animation-fix"
      }
    },
    {
      "name": "iosSimulatorArm64ApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../koalaplot-core-iossimulatorarm64/0.12.1-animation-fix/koalaplot-core-iossimulatorarm64-0.12.1-animation-fix.module",
        "group": "io.github.koalaplot",
        "module": "koalaplot-core-iossimulatorarm64",
        "version": "0.12.1-animation-fix"
      }
    },
    {
      "name": "iosSimulatorArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../koalaplot-core-iossimulatorarm64/0.12.1-animation-fix/koalaplot-core-iossimulatorarm64-0.12.1-animation-fix.module",
        "group": "io.github.koalaplot",
        "module": "koalaplot-core-iossimulatorarm64",
        "version": "0.12.1-animation-fix"
      }
    },
    {
      "name": "iosSimulatorArm64ResourcesElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.libraryelements": "kotlin-multiplatformresources",
        "org.gradle.usage": "kotlin-multiplatformresources",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../koalaplot-core-iossimulatorarm64/0.12.1-animation-fix/koalaplot-core-iossimulatorarm64-0.12.1-animation-fix.module",
        "group": "io.github.koalaplot",
        "module": "koalaplot-core-iossimulatorarm64",
        "version": "0.12.1-animation-fix"
      }
    },
    {
      "name": "iosSimulatorArm64MetadataElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../koalaplot-core-iossimulatorarm64/0.12.1-animation-fix/koalaplot-core-iossimulatorarm64-0.12.1-animation-fix.module",
        "group": "io.github.koalaplot",
        "module": "koalaplot-core-iossimulatorarm64",
        "version": "0.12.1-animation-fix"
      }
    },
    {
      "name": "jsApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "available-at": {
        "url": "../../koalaplot-core-js/0.12.1-animation-fix/koalaplot-core-js-0.12.1-animation-fix.module",
        "group": "io.github.koalaplot",
        "module": "koalaplot-core-js",
        "version": "0.12.1-animation-fix"
      }
    },
    {
      "name": "jsRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "available-at": {
        "url": "../../koalaplot-core-js/0.12.1-animation-fix/koalaplot-core-js-0.12.1-animation-fix.module",
        "group": "io.github.koalaplot",
        "module": "koalaplot-core-js",
        "version": "0.12.1-animation-fix"
      }
    },
    {
      "name": "jsSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "available-at": {
        "url": "../../koalaplot-core-js/0.12.1-animation-fix/koalaplot-core-js-0.12.1-animation-fix.module",
        "group": "io.github.koalaplot",
        "module": "koalaplot-core-js",
        "version": "0.12.1-animation-fix"
      }
    },
    {
      "name": "jsResourcesElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.libraryelements": "kotlin-multiplatformresourcesjs",
        "org.gradle.usage": "kotlin-multiplatformresourcesjs",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "available-at": {
        "url": "../../koalaplot-core-js/0.12.1-animation-fix/koalaplot-core-js-0.12.1-animation-fix.module",
        "group": "io.github.koalaplot",
        "module": "koalaplot-core-js",
        "version": "0.12.1-animation-fix"
      }
    },
    {
      "name": "wasmJsApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "wasm",
        "org.jetbrains.kotlin.wasm.target": "js"
      },
      "available-at": {
        "url": "../../koalaplot-core-wasm-js/0.12.1-animation-fix/koalaplot-core-wasm-js-0.12.1-animation-fix.module",
        "group": "io.github.koalaplot",
        "module": "koalaplot-core-wasm-js",
        "version": "0.12.1-animation-fix"
      }
    },
    {
      "name": "wasmJsRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.platform.type": "wasm",
        "org.jetbrains.kotlin.wasm.target": "js"
      },
      "available-at": {
        "url": "../../koalaplot-core-wasm-js/0.12.1-animation-fix/koalaplot-core-wasm-js-0.12.1-animation-fix.module",
        "group": "io.github.koalaplot",
        "module": "koalaplot-core-wasm-js",
        "version": "0.12.1-animation-fix"
      }
    },
    {
      "name": "wasmJsSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.platform.type": "wasm",
        "org.jetbrains.kotlin.wasm.target": "js"
      },
      "available-at": {
        "url": "../../koalaplot-core-wasm-js/0.12.1-animation-fix/koalaplot-core-wasm-js-0.12.1-animation-fix.module",
        "group": "io.github.koalaplot",
        "module": "koalaplot-core-wasm-js",
        "version": "0.12.1-animation-fix"
      }
    },
    {
      "name": "wasmJsResourcesElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.libraryelements": "kotlin-multiplatformresourcesjs",
        "org.gradle.usage": "kotlin-multiplatformresourcesjs",
        "org.jetbrains.kotlin.platform.type": "wasm",
        "org.jetbrains.kotlin.wasm.target": "js"
      },
      "available-at": {
        "url": "../../koalaplot-core-wasm-js/0.12.1-animation-fix/koalaplot-core-wasm-js-0.12.1-animation-fix.module",
        "group": "io.github.koalaplot",
        "module": "koalaplot-core-wasm-js",
        "version": "0.12.1-animation-fix"
      }
    }
  ]
}
