{
  "formatVersion": "1.1",
  "component": {
    "url": "../../koalaplot-core/0.12.1-animation-fix/koalaplot-core-0.12.1-animation-fix.module",
    "group": "io.github.koalaplot",
    "module": "koalaplot-core",
    "version": "0.12.1-animation-fix",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.4.1"
    }
  },
  "variants": [
    {
      "name": "androidApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.compose.ui",
          "module": "ui",
          "version": {
            "requires": "1.11.1"
          }
        },
        {
          "group": "org.jetbrains.compose.animation",
          "module": "animation",
          "version": {
            "requires": "1.11.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.4.10"
          }
        }
      ],
      "files": [
        {
          "name": "koalaplot-core.aar",
          "url": "koalaplot-core-android-0.12.1-animation-fix.aar",
          "size": 937409,
          "sha512": "8cea467b27d3ddee43e68f9d735fa1e38b3ac61cdcf4035c224d23edc6793c9fa606f6c547f7ca9d3ef52636b81f615cf47d24b73a16c2547e8b21855da0d400",
          "sha256": "26a1667435b2a7145fb91282035f4e1073e6992d9bca0ee21f25910167ff0bce",
          "sha1": "3e4113ee3aea70f346ab1395eb2012e754d11e17",
          "md5": "e78205f42ab23d3f11c58cceb0745686"
        }
      ]
    },
    {
      "name": "androidRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.compose.ui",
          "module": "ui",
          "version": {
            "requires": "1.11.1"
          }
        },
        {
          "group": "org.jetbrains.compose.animation",
          "module": "animation",
          "version": {
            "requires": "1.11.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.4.10"
          }
        },
        {
          "group": "org.jetbrains.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.11.1"
          }
        },
        {
          "group": "org.jetbrains.compose.foundation",
          "module": "foundation",
          "version": {
            "requires": "1.11.1"
          }
        },
        {
          "group": "org.jetbrains.compose.material3",
          "module": "material3",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.11.0"
          }
        }
      ],
      "files": [
        {
          "name": "koalaplot-core.aar",
          "url": "koalaplot-core-android-0.12.1-animation-fix.aar",
          "size": 937409,
          "sha512": "8cea467b27d3ddee43e68f9d735fa1e38b3ac61cdcf4035c224d23edc6793c9fa606f6c547f7ca9d3ef52636b81f615cf47d24b73a16c2547e8b21855da0d400",
          "sha256": "26a1667435b2a7145fb91282035f4e1073e6992d9bca0ee21f25910167ff0bce",
          "sha1": "3e4113ee3aea70f346ab1395eb2012e754d11e17",
          "md5": "e78205f42ab23d3f11c58cceb0745686"
        }
      ]
    },
    {
      "name": "androidSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "android",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "files": [
        {
          "name": "koalaplot-core-android-0.12.1-animation-fix-sources.jar",
          "url": "koalaplot-core-android-0.12.1-animation-fix-sources.jar",
          "size": 146947,
          "sha512": "93a706709f0c2c6d9dccdfe162450313dce2a06e29f137ab9a475f83bd35c9059f1ed0f12f71e3e808ccc5aa5b5949687f83d12cd340ee8465161421ad65580a",
          "sha256": "ea8f23df732181d856d10ab79e232c37bde6b52f506347b83b323623ec5bb550",
          "sha1": "add27542d737920eebf9ed08e2f2f4f1e32b3093",
          "md5": "98b483b909112b93eab0ecee29b3208d"
        }
      ]
    }
  ]
}
