name: Build

on: [push, pull_request]

jobs:
  android:
    name: Build Android & Run JVM Tests
    timeout-minutes: 40
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4.0.0
      - name: Build Android App
        run: ./gradlew composeApp:assembleDebug
      - name: Run JVM Tests
        run: ./gradlew domain:jvmTest
  ios:
    name: Build iOS
    timeout-minutes: 40
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4.0.0

      - name: Build iOS
        run: |
          cd iosApp
          
          xcrun xcodebuild \
            -scheme "iosApp" \
            -configuration "Debug" \
            -sdk "iphoneos" \
            -destination "generic/platform=iOS" \
            -allowProvisioningUpdates \
            OBJROOT=./build/ios \
            SYMROOT=./build/ios \
            CODE_SIGNING_ALLOWED=NO \
          | xcpretty
